# -*- coding: utf-8 -*-
"""SpamEmailAT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDq3PDbiKhhHUva8mgX6_oRtwWkyARvi
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import string
import nltk
from nltk.corpus import stopwords
from wordcloud import WordCloud
nltk.download('stopwords')

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.metrics import Precision, Recall


import warnings
warnings.filterwarnings('ignore')

"""#import text"""

data = pd.read_csv('Emails.csv')
data.head()

data.shape

"""#visualise the data"""

sns.countplot(x='label', data=data)
plt.show()

"""#Balance the DataSet
we use the same seed and part of the dataset to get consistant and replicable results. We could change it to be random every time, but that only applies if we are training a dataset. For us, this would only lead to different levels of accuracy.
"""

ham_msg = data[data['label'] == 'ham']
spam_msg = data[data['label'] == 'spam']

# Downsample Ham emails to match the number of Spam emails
ham_msg_balanced = ham_msg.sample(n=len(spam_msg), random_state=42)

# Combine balanced data
balanced_data = pd.concat([ham_msg_balanced, spam_msg]).reset_index(drop=True)

# Visualize the balanced dataset
sns.countplot(x='label', data=balanced_data)
plt.title("Balanced Distribution of Spam and Ham Emails")
plt.xticks(ticks=[0, 1], labels=['Ham (Not Spam)', 'Spam'])
plt.show()

"""Stemming --> reducing words to their base or root form to help catagorise words. This is based on prefixes and suffixes. eg chocolates = chocolate and running = run but better =/= good.

Lemmatization --> using the meaning instead of just prefixes and suffixes to transform words into their root form. running = run & better = good.

"""

#remove stopwords
#remove punctuation
balanced_data['text'] = balanced_data['text'].str.replace('Subject', '')
balanced_data.head()

#removing punctuation
punctuations_list = string.punctuation
def remove_punctuations(text):
    temp = str.maketrans('', '', punctuations_list)
    return text.translate(temp)

balanced_data['text']= balanced_data['text'].apply(lambda x: remove_punctuations(x))
balanced_data.head()

#removing stopwords
def remove_stopwords(text):
    stop_words = stopwords.words('english')

    imp_words = []

    # Storing the important words
    for word in str(text).split():
        word = word.lower()

        if word not in stop_words:
            imp_words.append(word)

    output = " ".join(imp_words)

    return output


balanced_data['text'] = balanced_data['text'].apply(lambda text: remove_stopwords(text))
balanced_data.head()

"""Creating a word cloud so we as the developer can get an insight into what is in each dataset. This is more of something for our understanding instead of something we did for the actual code."""

def plot_word_cloud(data, typ):
    email_corpus = " ".join(data['text'])
    wc = WordCloud(background_color='black', max_words=100, width=800, height=400).generate(email_corpus)
    plt.figure(figsize=(7, 7))
    plt.imshow(wc, interpolation='bilinear')
    plt.title(f'WordCloud for {typ} Emails', fontsize=15)
    plt.axis('off')
    plt.show()

plot_word_cloud(balanced_data[balanced_data['label'] == 'ham'], typ='Non-Spam')
plot_word_cloud(balanced_data[balanced_data['label'] == 'spam'], typ='Spam')

"""#Tokenisation and Padding
converts the processed text data into integers so the model can understand them.
tokenisation --> turns each word into a unique integer.

padding --> the text sequences are then each the same length, making it easy to understand what is spam and what is ham without having to read through more data than is necessary and thus is compatible with this model
"""

train_X, test_X, train_Y, test_Y = train_test_split(
    balanced_data['text'], balanced_data['label'], test_size=0.2, random_state=42
)

tokenizer = Tokenizer()
tokenizer.fit_on_texts(train_X)

train_sequences = tokenizer.texts_to_sequences(train_X)
test_sequences = tokenizer.texts_to_sequences(test_X)

max_len = 100  # Maximum sequence length
train_sequences = pad_sequences(train_sequences, maxlen=max_len, padding='post', truncating='post')
test_sequences = pad_sequences(test_sequences, maxlen=max_len, padding='post', truncating='post')

train_Y = (train_Y == 'spam').astype(int)
test_Y = (test_Y == 'spam').astype(int)

"""#Define the Model
This uses Sequential architecture
Embedding Layer --> learns the vector representations of words

LSTM layer --> captures patterns in sequences

Fully connected Layer--> Extracts relevant features

Output Layer --> predicts whether an email is spam or not.
"""

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=32, input_length=max_len),
    tf.keras.layers.LSTM(16),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer
])

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

"""#Train The Model
We train the model using **EarlyStopping** and **ReduceLROnPlateau** callbacks. These callbacks help stop the training early if the model’s performance doesn’t improve and reduce the learning rate to fine-tune the model.
"""

es = EarlyStopping(patience=3, monitor='val_accuracy', restore_best_weights=True)
lr = ReduceLROnPlateau(patience=2, monitor='val_loss', factor=0.5, verbose=0)

history = model.fit(
    train_sequences, train_Y,
    validation_data=(test_sequences, test_Y),
    epochs=20,
    batch_size=32,
    callbacks=[lr, es]
)

"""Early Stopping was used, meaning only 9 epochs were executed in this case, but this is subject to change

Evaluate the test data to measure performance
"""

# First, get the loss and accuracy from model.evaluate
test_loss, test_accuracy = model.evaluate(test_sequences, test_Y)

# Then, make predictions to calculate precision and recall separately.
y_pred_probs = model.predict(test_sequences)
y_pred = (y_pred_probs > 0.5).astype(int)

# Initialize and update the Precision and Recall metrics
m_precision = Precision()
m_recall = Recall()

m_precision.update_state(test_Y, y_pred)
m_recall.update_state(test_Y, y_pred)

test_precision = m_precision.result().numpy()
test_recall = m_recall.result().numpy()

print('Test Loss :',test_loss)
print('Test Accuracy :',test_accuracy)
print("Test Precision:", test_precision)
print("Test Recall:", test_recall)

"""loss = how many were wrong. If there is a low loss number, it means that the model got very few guesses wrong.

accuracy = how many out of the total guesses were correct.

precision = how many false postives would this model get? having a high precision means that the model has very few false positives.

recall = false negatives. If there is a high recall, it means that very few true emails got marked as spam.

Plot graphs to depict the cariance of training and valudation by how many epochs

#Graph to prove accuracy
"""

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()
plt.show()